create database if not exists G1_Car_Insurance;
use G1_Car_Insurance;

CREATE TABLE IF NOT EXISTS G1_CUSTOMER (
  G1_CUST_ID INT NOT NULL,
  G1_CUST_FNAME VARCHAR(45) ,
  G1_CUST_LNAME VARCHAR(45),
  G1_CUST_DOB DATE,
  G1_CUST_GENDER ENUM("M", "F"),
  G1_CUST_ADDRESS VARCHAR(45),
  G1_CUST_EMAIL VARCHAR(45),
  G1_CUST_MOB_NUMBER INT,
  G1_CUST_PASSPORT_NUMBER VARCHAR(45),
  G1_CUST_MARITAL_STATUS VARCHAR(45),
  G1_CUST_PPS_NUMBER INT,
  PRIMARY KEY (G1_CUST_ID)
  );

CREATE TABLE IF NOT EXISTS G1_MEMBERSHIP (
  G1_MEMBERSHIP_ID INT NOT NULL,
  G1_MEMBERSHIP_TYPE VARCHAR(45),
  G1_ORGANISATION_CONTACT INT,
  PRIMARY KEY (G1_MEMBERSHIP_ID)
  );

CREATE TABLE IF NOT EXISTS G1_PREMIUM (
  G1_PREMIUM_PAYMENT_ID INT NOT NULL,
  G1_CUST_ID INT,
  G1_POLICY_NUMBER INT ,
  G1_PREMIUM_PAYMENT_SCHEDULE DATE,
  G1_PREMIUM_PAYMENT_AMOUNT INT,
  PRIMARY KEY (G1_PREMIUM_PAYMENT_ID),
  FOREIGN KEY (G1_CUST_ID)
  REFERENCES G1_CUSTOMER (G1_CUST_ID)
  );

CREATE TABLE IF NOT EXISTS G1_CLAIM (
  G1_CLAIM_ID INT NOT NULL,
  G1_CUST_ID INT,
  G1_CLAIM_AMOUNT INT,
  G1_INCIDENT_ID INT,
  G1_DAMAGE_TYPE VARCHAR(45),
  G1_DATE_OF_CLAIM DATE,
  G1_CLAIM_STATUS VARCHAR(45),
  PRIMARY KEY (G1_CLAIM_ID),
  FOREIGN KEY (G1_CUST_ID)
  REFERENCES G1_CUSTOMER (G1_CUST_ID)
  );

CREATE TABLE IF NOT EXISTS G1_VEHICLE (
  G1_VEHICLE_ID INT NOT NULL,
  G1_CUST_ID INT,
  G1_POLICY_ID INT,
  G1_DEPENDENT_NOK_ID INT,
  G1_VEHICLE_REGISTRATION_NUMBER INT,
  G1_VEHICLE_VALUE INT,
  G1_VEHICLE_TYPE VARCHAR(45),
  G1_VEHICLE_SIZE INT,
  G1_VEHICLE_NUMBER_OF_SEAT INT,
  G1_VEHICLE_MANUFACTURER VARCHAR(45),
  G1_VEHICLE_ENGINE_NUMBER VARCHAR(45),
  G1_VEHICLE_CHASIS_NUMBER VARCHAR(45),
  G1_VEHICLE_NUMBER VARCHAR(45),
  G1_VEHICLE_MODEL_NUMBER VARCHAR(45),
  PRIMARY KEY (G1_VEHICLE_ID),
    FOREIGN KEY (G1_CUST_ID)
    REFERENCES G1_CUSTOMER (G1_CUST_ID)
	);

CREATE TABLE IF NOT EXISTS G1_SETTLEMENT (
  G1_CLAIM_SETTLEMENT_ID INT NOT NULL,
  G1_CLAIM_ID INT,
  G1_DATE_SETTLED DATE,
  G1_AMOUNT_PAID INT,
  PRIMARY KEY (G1_CLAIM_SETTLEMENT_ID),
    FOREIGN KEY (G1_CLAIM_ID)
    REFERENCES G1_CLAIM (G1_CLAIM_ID)
    );

CREATE TABLE IF NOT EXISTS G1_STAFF (
  G1_STAFF_ID INT NOT NULL,
  G1_STAFF_FNAME VARCHAR(45),
  G1_STAFF_LNAME VARCHAR(45),
  G1_STAFF_ADDRESS VARCHAR(45),
  G1_STAFF_CONTACT INT,
  G1_STAFF_GENDER ENUM("M","F"),
  G1_STAFF_NATIONALITY VARCHAR(45),
  G1_STAFF_QUALIFICATION VARCHAR(45),
  G1_STAFF_ALLOWANCE INT,
  G1_STAFF_PPS_NUMBER INT,
  G1_STAFF_MARITAL_STATUS VARCHAR(45),
  PRIMARY KEY (G1_STAFF_ID)
  );

CREATE TABLE IF NOT EXISTS G1_APPLICATION (
  G1_APPLICATION_ID INT NOT NULL,
  G1_CUST_ID INT,
  G1_VEHICLE_ID INT,
  G1_COVERAGE VARCHAR(80),
  PRIMARY KEY (G1_APPLICATION_ID),
  FOREIGN KEY (G1_CUST_ID)
  REFERENCES G1_CUSTOMER (G1_CUST_ID)
  );

CREATE TABLE IF NOT EXISTS G1_INSURANCE_POLICY (
  G1_AGREEMENT_ID INT NOT NULL,
  G1_APPLICATION_ID INT,
  G1_POLICY_NUMBER INT,
  G1_START_DATE DATE,
  G1_EXPIRY_DATE DATE,
  G1_TERM_CONDITION_DESCRIPTION VARCHAR(500),
  PRIMARY KEY (G1_AGREEMENT_ID),
  FOREIGN KEY (G1_APPLICATION_ID)
  REFERENCES G1_APPLICATION (G1_APPLICATION_ID)
  );

CREATE TABLE IF NOT EXISTS G1_INSURANCE_POLICY_COVERAGE (
  G1_IPC_ID INT NOT NULL,
  G1_AGREEMENT_ID INT,
  G1_IPC_CLAIM_DATE DATE,
  G1_IPC_CLAIM_REASON VARCHAR(200),
  PRIMARY KEY (G1_IPC_ID),
  FOREIGN KEY (G1_AGREEMENT_ID)
  REFERENCES G1_INSURANCE_POLICY (G1_AGREEMENT_ID)
  );

CREATE TABLE IF NOT EXISTS G1_DEPARTMENT (
  G1_DEPARTMENT_NAME VARCHAR(20) NOT NULL,
  G1_IPC_ID INT,
  G1_CONTACT_INFORMATION VARCHAR(45),
  G1_DEPARTMENT_STAFF VARCHAR(45),
  G1_DEPARTMENT_LEADER VARCHAR(45),
  PRIMARY KEY (G1_DEPARTMENT_NAME),
  FOREIGN KEY (G1_IPC_ID)
  REFERENCES G1_INSURANCE_POLICY_COVERAGE (G1_IPC_ID)
  );

CREATE TABLE IF NOT EXISTS G1_OFFICE (
  G1_OFFICE_NAME VARCHAR(20) NOT NULL,
  G1_OFFICE_LEADER VARCHAR(45),
  G1_CONTACT_INFORMATION VARCHAR(45),
  G1_ADDRESS VARCHAR(45),
  G1_ADMIN_COST INT,
  G1_STAFF VARCHAR(45),
  PRIMARY KEY (G1_OFFICE_NAME)
  );

CREATE TABLE IF NOT EXISTS G1_SERVICE (
  G1_VEHICLE_SERVICE VARCHAR(20) NOT NULL,
  G1_IPC_ID INT,
  G1_VEHICLE_SERVICE_ADDRESS VARCHAR(200),
  G1_VEHICLE_SERVICE_CONTACT INT,
  G1_VEHICLE_SERVICE_INCHARGE VARCHAR(45),
  G1_VEHICLE_SERVICE_TYPE VARCHAR(45),
  PRIMARY KEY (G1_VEHICLE_SERVICE),
  FOREIGN KEY (G1_IPC_ID)
  REFERENCES G1_INSURANCE_POLICY_COVERAGE (G1_IPC_ID)
  );

CREATE TABLE IF NOT EXISTS G1_NOK (
  G1_NOK_ID INT NOT NULL,
  G1_AGREEMENT_ID INT,
  G1_NOK_NAME VARCHAR(45),
  G1_NOK_ADDRESS VARCHAR(45),
  G1_NOK_PHONE_NUMBER INT,
  G1_NOK_MARITAL_STATUS VARCHAR(45),
  G1_NOK_GENDER ENUM("M", "F"),
  PRIMARY KEY (G1_NOK_ID),
  FOREIGN KEY (G1_AGREEMENT_ID)
  REFERENCES G1_INSURANCE_POLICY (G1_AGREEMENT_ID)
  );

CREATE TABLE IF NOT EXISTS G1_COMPANY (
  G1_COMPANY_NAME VARCHAR(20) NOT NULL,
  G1_COMPANY_ADDRESS VARCHAR(45),
  G1_COMPANY_CONTACT_NUMBER INT,
  G1_COMPANY_FAX INT,
  G1_COMPANY_EMAIL VARCHAR(45),
  G1_COMPANY_WEBSITE VARCHAR(45),
  G1_COMPANY_LOCATION VARCHAR(45),
  G1_COMPANY_DEPARTMENT_NAME VARCHAR(45),
  G1_COMPANY_OFFICE_NAME VARCHAR(45),
  G1_DEPARTMENT_NAME VARCHAR(45),
  PRIMARY KEY (G1_COMPANY_NAME),
  FOREIGN KEY (G1_DEPARTMENT_NAME)
  REFERENCES G1_DEPARTMENT (G1_DEPARTMENT_NAME)
  );

CREATE TABLE IF NOT EXISTS G1_TERMS_CONDITIONS (
  G1_COVERAGE_ID INT NOT NULL,
  G1_COVERAGE_AMOUNT INT,
  G1_COVERAGE_TYPE VARCHAR(45),
  G1_COVERAGE_LEVEL VARCHAR(45),
  G1_PRODUCT_ID VARCHAR(45),
  G1_COVERAGE_DESCRIPTION VARCHAR(45),
  G1_COVERAGE_TERMS VARCHAR(45),
  PRIMARY KEY (G1_COVERAGE_ID)
  );

CREATE TABLE IF NOT EXISTS G1_RECEIPT (
  G1_RECEIPT_ID INT NOT NULL,
  G1_PREMIUM_PAYMENT_ID INT,
  G1_COST INT,
  G1_TIME DATE,
  PRIMARY KEY (G1_RECEIPT_ID),
  FOREIGN KEY (G1_PREMIUM_PAYMENT_ID)
  REFERENCES G1_PREMIUM (G1_PREMIUM_PAYMENT_ID)
  );

CREATE TABLE IF NOT EXISTS G1_QUOTE (
  G1_QUOTE_ID INT NOT NULL,
  G1_APPLICATION_ID INT,
  G1_ISSUE_DATE DATE,
  G1_VALID_FROM_DATE DATE,
  G1_VALID_TILL_DATE DATE,
  G1_DESCRIPTION VARCHAR(45),
  G1_PRODUCT_ID VARCHAR(45),
  G1_COVERAGE_LEVEL VARCHAR(45),
  PRIMARY KEY (G1_QUOTE_ID),
  FOREIGN KEY (G1_APPLICATION_ID)
  REFERENCES G1_APPLICATION (G1_APPLICATION_ID)
  );

CREATE TABLE IF NOT EXISTS G1_CUSTOMER_MEMBERSHIP (
  G1_CUST_ID INT NOT NULL,
  G1_MEMBERSHIP_ID INT NOT NULL,
  PRIMARY KEY (G1_CUST_ID, G1_MEMBERSHIP_ID),
  FOREIGN KEY (G1_CUST_ID)
  REFERENCES G1_CUSTOMER (G1_CUST_ID),
  FOREIGN KEY (G1_MEMBERSHIP_ID)
  REFERENCES G1_MEMBERSHIP (G1_MEMBERSHIP_ID)
  );

CREATE TABLE IF NOT EXISTS G1_DEPARTMENT_OFFICE (
  G1_DEPARTMENT_NAME VARCHAR(20) NOT NULL,
  G1_OFFICE_NAME VARCHAR(20) NOT NULL,
  PRIMARY KEY (G1_DEPARTMENT_NAME, G1_OFFICE_NAME),
  FOREIGN KEY (G1_DEPARTMENT_NAME)
  REFERENCES G1_DEPARTMENT (G1_DEPARTMENT_NAME),
  FOREIGN KEY (G1_OFFICE_NAME)
  REFERENCES G1_OFFICE (G1_OFFICE_NAME)
  );

CREATE TABLE IF NOT EXISTS G1_COMPANY_STAFF (
  G1_COMPANY_NAME VARCHAR(20) NOT NULL,
  G1_STAFF_ID INT NOT NULL,
  PRIMARY KEY (G1_COMPANY_NAME, G1_STAFF_ID),
  FOREIGN KEY (G1_COMPANY_NAME)
  REFERENCES G1_COMPANY (G1_COMPANY_NAME),
  FOREIGN KEY (G1_STAFF_ID)
  REFERENCES G1_STAFF (G1_STAFF_ID)
  );

CREATE TABLE IF NOT EXISTS G1_INSURANCE_POLICY_TERMS_CONDITIONS (
  G1_AGREEMENT_ID INT NOT NULL,
  G1_COVERAGE_ID INT NOT NULL,
  PRIMARY KEY (G1_AGREEMENT_ID, G1_COVERAGE_ID),
  FOREIGN KEY (G1_AGREEMENT_ID)
  REFERENCES G1_INSURANCE_POLICY (G1_AGREEMENT_ID),
  FOREIGN KEY (G1_COVERAGE_ID)
  REFERENCES G1_TERMS_CONDITIONS (G1_COVERAGE_ID)
  );

